server:
  port: 9090

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
  cache:
    redis:
      cache-null-values: false
      key-prefix: spring-cache
      time-to-live: 0
      use-key-prefix: true
